import requests
import folium
import json

'''get_photos function: takes a tag, a count and an output_file as parameters and returns the most count recent 
photos from Flickr with the given tag. The output file saves the json generated by the Flicker API.
'''


def get_photos(tag: str, count: int, output_file: str = "outputdata.json") -> folium.Map:
    url = 'https://api.flickr.com/services/rest/'
    params = {
        'method': 'flickr.photos.search',
        'api_key': 'a7d50a45916d6f2daaf0eaa86801addf',
        'tags': tag,
        'format': 'json',
        'nojsoncallback': 1,
        'sort': 'date-posted-desc',
        'per_page': 500,
        'extras': 'geo'
    }
    response = requests.get(url, params=params)
    data = response.json()
    if output_file:
        with open(output_file, 'w') as f:
            json.dump(data, f)

    photos = data['photos']['photo']

    filtered_photos = [photo for photo in photos if 'latitude' in photo and 'longitude' in photo]
    placed = 0
    locations_map = folium.Map(location=[0, 0], zoom_start=2)

    coordinate_counter = {}
    for photo in filtered_photos:
        if placed == count:
            break
        coordinate = (photo['latitude'], photo['longitude'])
        if photo['latitude'] != 0 and photo['longitude'] != 0:
            if coordinate not in coordinate_counter:
                coordinate_counter[coordinate] = 1
            else:
                coordinate_counter[coordinate] += 1

            filtered_photo_ids = ', '.join(
                str(photo['id'])
                for photo in filtered_photos
                if (photo['latitude'], photo['longitude']) == coordinate
            )
            marker_popup = f"Coordinates: {coordinate}<br>Photo IDs: {filtered_photo_ids}"

            folium.Marker(
                location=[float(photo['latitude']), float(photo['longitude'])],
                popup=marker_popup
            ).add_to(locations_map)
            print(f"{placed}: Placed photo with id:{photo['id']}, coordinates: {coordinate}")
            placed += 1

    return locations_map


t = input("Enter the tag: ")
cnt = int(input("Enter the count: "))

generated_map = get_photos(t, cnt)
generated_map.save('map.html')
